Algoritmo "semnome"

Var
   quantos, valor, contador: inteiro


Inicio
      contador <- 0
      Escreva("Quer contar ate quantos? ")
      Leia (valor)
      Escreva("Quer contar de quantos em quantos?")
      Leia(quantos)
      Enquanto (contador<= valor) faca
        Escreval(contador)
        contador <- contador + quantos
      Fimenquanto
      ESCREVAL("Terminei de contar")
      


Fimalgoritmo